import { DefaultExpenseCategory } from '@/types/money';

const KEYWORD_MAP: Record<DefaultExpenseCategory, string[]> = {
  Education: [
    'book',
    'books',
    'notebook',
    'notebooks',
    'pen',
    'pens',
    'pencil',
    'stationery',
    'xerox',
    'print',
    'printing',
    'photocopy',
    'tuition',
    'course',
    'exam',
    'examination',
    'lab',
    'manual',
    'library',
    'calculator',
    'textbook',
    'notes',
    'paper',
    'assignment',
    'udemy',
    'coursera',
  ],
  Entertainment: [
    'movie ticket',
    'cinema ticket',
    'theatre ticket',
    'concert ticket',
    'show ticket',
    'movie',
    'movies',
    'cinema',
    'netflix',
    'spotify',
    'prime',
    'game',
    'gaming',
    'steam',
    'party',
    'club',
    'theatre',
    'pvr',
    'inox',
    'concert',
    'outing',
    'bowling',
  ],
  Travel: [
    'bus ticket',
    'train ticket',
    'flight ticket',
    'metro ticket',
    'bus',
    'train',
    'metro',
    'cab',
    'auto',
    'ticket',
    'tickets',
    'uber',
    'ola',
    'rapido',
    'petrol',
    'diesel',
    'flight',
    'plane',
    'air',
    'toll',
    'fare',
    'rickshaw',
    'travel',
    'irctc',
    'railway',
    'dehradun',
    'delhi',
    'mumbai',
    'pune',
    'bangalore',
    'airport',
    'station',
  ],
  Food: [
    'food',
    'lunch',
    'dinner',
    'breakfast',
    'brunch',
    'coffee',
    'tea',
    'chai',
    'mess',
    'canteen',
    'swiggy',
    'zomato',
    'snack',
    'snacks',
    'pizza',
    'burger',
    'cafe',
    'maggi',
    'juice',
    'samosa',
    'biryani',
    'dosa',
    'thali',
    'groceries',
    'grocery',
    'milk',
    'biscuit',
    'biscuits',
    'fruit',
    'fruits',
  ],
  Shopping: [
    'clothes',
    'shoes',
    'shoe',
    'bag',
    'backpack',
    'shirt',
    'tshirt',
    't-shirt',
    'jeans',
    'pants',
    'jacket',
    'hoodie',
    'dress',
    'amazon',
    'flipkart',
    'myntra',
    'zara',
    'h&m',
    'watch',
    'wallet',
  ],
  Bills: [
    'wifi',
    'wi-fi',
    'internet',
    'recharge',
    'mobile',
    'electricity',
    'power',
    'rent',
    'room rent',
    'bill',
    'bills',
    'water',
    'gas',
    'cylinder',
    'jio',
    'airtel',
    'vi',
    'broadband',
    'laundry',
    'washing',
  ],
  Other: [],
};

export function detectExpenseCategory(text: string): DefaultExpenseCategory {
  if (!text || typeof text !== 'string') return 'Other';

  const cleaned = text.toLowerCase().trim();
  const words = cleaned.split(/[\s,._\-+/]+/).filter(Boolean);

  // Pass 1: Multi-word phrase matching across all categories
  for (const [category, keywords] of Object.entries(KEYWORD_MAP) as [DefaultExpenseCategory, string[]][]) {
    for (const kw of keywords) {
      if (kw.includes(' ') && cleaned.includes(kw)) {
        return category;
      }
    }
  }

  // Pass 2: Single word matching
  for (const [category, keywords] of Object.entries(KEYWORD_MAP) as [DefaultExpenseCategory, string[]][]) {
    for (const kw of keywords) {
      if (!kw.includes(' ') && words.includes(kw)) {
        return category;
      }
    }
  }

  return 'Other';
}
